### ISSUE TITLE
[BUG] - README links point to the wrong location

### ISSUE THREAD

**Issue by sidpalas** [vultr/helm-charts#3]
**Describe the bug**
Links to CSI and CCM helm charts are switched in README.md

**To Reproduce**
1. Go to README
2. Click on link to each of the helm charts
3. See that you are navigated to the wrong chart

**Expected behavior**
Link navigates to correct chart

**Comment by ddymko** [comment]
@sidpalas Thanks for creating the ticket! This clearly slipped past me.
